// Generated by CoffeeScript 1.4.0
(function() {
  var Heron, c_max_reconnect_retry, receive, reconnect, _ref;

  Heron = (_ref = this.Heron) != null ? _ref : this.Heron = {};

  c_max_reconnect_retry = 1;

  reconnect = function() {
    receive.call(this);
    jQuery.get(this.__.path + "/flush", {
      client_id: this.__.client_id
    });
    return null;
  };

  receive = function() {
    var failure,
      _this = this;
    if (!this.__.connected) {
      return null;
    }
    failure = function() {
      if (!_this.__.connected) {
        return;
      }
      if (_this.__.reconnect_retry < c_max_reconnect_retry) {
        _this.__.verbose("disconnected; trying to reconnect.");
        ++_this.__.reconnect_retry;
        return setTimeout(function() {
          return reconnect.call(_this);
        }, 0);
      } else {
        _this.__.verbose("disconnected; retry count exceeded.");
        _this.__.connected = false;
        _this.__.current_receive = null;
        return jQuery(document).trigger("Heron.Comet:lost", _this);
      }
    };
    this.__.current_receive = jQuery.get(this.__.path + "/receive", {
      client_id: this.__.client_id
    }, function(data, textStatus, transport) {
      if (!_this.__.connected) {
        return;
      }
      if (transport.status !== 200) {
        return failure();
      } else if (_this.__.connected) {
        if (_this.__.reconnect_retry > 0) {
          _this.__.verbose("reconnected.");
          _this.__.reconnect_retry = 0;
        }
        if (transport.responseText !== "") {
          _this.__.verbose(transport.responseText);
          _this.__.on_message(transport.responseText, _this);
        }
        return setTimeout(function() {
          return receive.call(_this);
        }, 0);
      }
    }).fail(failure);
    return null;
  };

  Heron.Comet = (function() {

    function Comet(config) {
      var _ref1, _ref2, _ref3, _ref4, _ref5,
        _this = this;
      this.__ = {
        path: (_ref1 = config.path) != null ? _ref1 : "/comet",
        on_message: (_ref2 = config.on_message) != null ? _ref2 : function() {},
        on_verbose: (_ref3 = config.on_verbose) != null ? _ref3 : function() {},
        on_exception: (_ref4 = config.on_exception) != null ? _ref4 : function(e, text, comet) {
          return _this.__.verbose("Exception: " + text);
        },
        client_id: (_ref5 = config.client_id) != null ? _ref5 : Heron.Util.generate_id(),
        connected: false,
        verbose: function(s) {
          return _this.__.on_verbose("comet: " + s, _this);
        },
        reconnect_retry: 0
      };
      this.__.verbose("initialized");
    }

    Comet.prototype.client_id = function() {
      return this.__.client_id;
    };

    Comet.prototype.connected = function() {
      return this.__.connected;
    };

    Comet.prototype.connect = function() {
      var _this = this;
      jQuery.get(this.__.path + "/connect", {
        client_id: this.__.client_id
      }, function() {
        _this.__.connected = true;
        receive.call(_this);
        _this.__.verbose("connected");
        return jQuery(document).trigger("Heron.Comet:connected", _this);
      });
      return this;
    };

    Comet.prototype.disconnect = function() {
      var _ref1,
        _this = this;
      if (this.__.connected) {
        this.__.connected = false;
        if ((_ref1 = this.__.current_receive) != null) {
          _ref1.abort();
        }
        jQuery.get(this.__.path + "/disconnect", {
          client_id: this.__.client_id
        }, function() {
          _this.__.verbose("disconnected");
          return jQuery(document).trigger("Heron.Comet:disconnected", _this);
        });
      }
      return this;
    };

    return Comet;

  })();

}).call(this);
