// Generated by CoffeeScript 1.6.3
(function() {
  var Heron, Receiver, flush_partials, make_thingy, only_keys, send_create, send_create_subkey, send_update_subkey, split_key, subkey_key,
    __slice = [].slice;

  Heron = this.Heron != null ? this.Heron : this.Heron = {};

  only_keys = function(obj, keys) {
    var k, result, _i, _len;
    result = {};
    for (_i = 0, _len = keys.length; _i < _len; _i++) {
      k = keys[_i];
      if (obj[k] == null) {
        throw "Missing key " + k;
      }
      result[k] = obj[k];
    }
    return result;
  };

  subkey_key = function(id, subkey) {
    return "" + id + "." + subkey;
  };

  split_key = function(key) {
    var id, rest, _ref;
    _ref = key.split("."), id = _ref[0], rest = 2 <= _ref.length ? __slice.call(_ref, 1) : [];
    return [id, rest.join(".")];
  };

  send_update_subkey = function(thingy, subkey) {
    var attr_names, data, domain, key, type_data;
    type_data = this._.per_type[thingy.typename()];
    attr_names = type_data.subkeys[subkey];
    data = only_keys(thingy.get.apply(thingy, attr_names), attr_names);
    key = subkey_key(thingy.id(), subkey);
    domain = this._.domain;
    if (subkey === '_') {
      data = {
        typename: thingy.typename(),
        subkeys: Heron.Util.keys(type_data.subkeys),
        attrs: data
      };
    }
    this._.dictionary.update(this._.domain, key, data);
    return null;
  };

  send_create_subkey = function(thingy, subkey) {
    var attr_keys, id, key, type_data, typename, value;
    typename = thingy.typename();
    id = thingy.id();
    type_data = this._.per_type[typename];
    attr_keys = type_data.subkeys[subkey];
    key = subkey_key(id, subkey);
    value = only_keys(thingy.get.apply(thingy, attr_keys), attr_keys);
    if (subkey === '_') {
      value = {
        typename: typename,
        attrs: value
      };
    }
    return this._.dictionary.create(this._.domain, key, value);
  };

  send_create = function(thingy) {
    var id, type_data, typename,
      _this = this;
    typename = thingy.typename();
    id = thingy.id();
    type_data = this._.per_type[typename];
    this._.dictionary.batch(function() {
      var attr_keys, subkey, _ref;
      _ref = type_data.subkeys;
      for (subkey in _ref) {
        attr_keys = _ref[subkey];
        _this._.send_create_subkey(thingy, subkey);
      }
      return _this._.dictionary.create(_this._.domain, '%create', id);
    });
    return null;
  };

  make_thingy = function(typename, id, attrs, local_data, subkeys) {
    var real_subkeys, subkey, thingy, to_delete, to_push, _i, _len,
      _this = this;
    if (subkeys == null) {
      subkeys = null;
    }
    if (typename == null) {
      this._.on_error("Missing typename for thingy: " + id);
    }
    this._.make_guard = true;
    thingy = new Heron.Thingy(this, typename, id, attrs, local_data);
    this._.make_guard = false;
    if (subkeys != null) {
      real_subkeys = {};
      for (subkey in this._.per_type[typename].subkeys) {
        real_subkeys[subkey] = true;
      }
      to_delete = [];
      for (_i = 0, _len = subkeys.length; _i < _len; _i++) {
        subkey = subkeys[_i];
        if (real_subkeys[subkey]) {
          delete real_subkeys[subkey];
        } else {
          to_delete.push(subkey);
        }
      }
      to_push = Heron.Util.keys(real_subkeys);
      this._.dictionary.batch(function() {
        var _j, _k, _len1, _len2, _results;
        for (_j = 0, _len1 = to_delete.length; _j < _len1; _j++) {
          subkey = to_delete[_j];
          _this._.dictionary["delete"](_this.domain(), subkey);
        }
        _results = [];
        for (_k = 0, _len2 = to_push.length; _k < _len2; _k++) {
          subkey = to_push[_k];
          _results.push(_this._.send_create_subkey(thingy, subkey));
        }
        return _results;
      });
    }
    return thingy;
  };

  flush_partials = function() {
    var id, info, _ref;
    _ref = this._.partials;
    for (id in _ref) {
      info = _ref[id];
      this._.make_thingy(info.typename, id, info.attrs, false, this._.partials_subkeys[id]);
    }
    this._.partials = {};
    this._.partials_subkeys = {};
    return null;
  };

  Receiver = (function() {
    function Receiver(thingyverse) {
      this._ = thingyverse._;
    }

    Receiver.prototype.create = function(domain, key, value) {
      var attrs, id, info, k, partial_attrs, subkey, v, _base, _base1, _base2, _ref;
      if ((this._.dictionary == null) || domain !== this._.domain) {
        return null;
      }
      if (key === '_synced') {
        if (this._.ready) {
          this._.flush_partials();
        } else {
          for (k in this._.partials) {
            this._.partials_to_create[k] = true;
          }
        }
        this._.on_sync();
        this._.synced = true;
      } else if (key === '%create') {
        if (this._.ready) {
          id = value;
          info = this._.partials[id];
          if (info == null) {
            this._.on_error("Missing everything for thingy: " + id);
          } else {
            if (this._.ready) {
              this._.make_thingy(info.typename, id, info.attrs, false, this._.partials_subkeys[id]);
            } else {
              this._.partials_to_create[id] = true;
            }
          }
          delete this._.partials[id];
          delete this._.partials_subkeys[id];
        }
      } else if (key[0] !== '_') {
        _ref = split_key(key), id = _ref[0], subkey = _ref[1];
        if (this._.per_thingy[id] != null) {
          return;
        }
        attrs = value;
        if ((_base = this._.partials)[id] == null) {
          _base[id] = {};
        }
        ((_base1 = this._.partials_subkeys)[id] != null ? (_base1 = this._.partials_subkeys)[id] : _base1[id] = []).push(subkey);
        if (subkey === '_') {
          if (value.typename == null) {
            this._.on_error("Cannot understand basekey " + key + ".  No typename.");
          }
          if (value.attrs == null) {
            this._.on_error("Cannot understand basekey " + key + ".  No attrs.");
          }
          if (this._.per_type[value.typename] == null) {
            this._.on_error("Received basekey " + key + " for unknown typename: " + value.typename + ".");
          }
          this._.partials[id].typename = value.typename;
          attrs = value.attrs;
        }
        partial_attrs = (_base2 = this._.partials[id]).attrs != null ? (_base2 = this._.partials[id]).attrs : _base2.attrs = {};
        for (k in attrs) {
          v = attrs[k];
          partial_attrs[k] = v;
        }
      }
      return null;
    };

    Receiver.prototype.update = function(domain, key, value) {
      var id, k, subkey, thingy_data, type_data, v, _ref;
      _ref = split_key(key), id = _ref[0], subkey = _ref[1];
      thingy_data = this._.per_thingy[id];
      if (domain !== this._.domain) {
        this._.on_error("Received message for unknown domain: " + domain + ".");
        return null;
      }
      if (subkey === '_') {
        value = value.attrs;
      }
      if (thingy_data == null) {
        if (this._.partials[id]) {
          for (k in value) {
            v = value[k];
            this._.partials[id][k] = v;
          }
        }
        return null;
      }
      type_data = this._.per_type[thingy_data.thingy.typename()];
      if (type_data.subkeys[subkey] == null) {
        this._.on_error("Received update for non-existent subkey " + subkey + ": " + key);
        return null;
      }
      thingy_data.delegate.set(thingy_data.thingy, value, false);
      return null;
    };

    Receiver.prototype["delete"] = function(domain, key) {
      var id, subkey, thingy_data, _ref;
      _ref = split_key(key), id = _ref[0], subkey = _ref[1];
      thingy_data = this._.per_thingy[id];
      if (domain !== this._.domain) {
        this._.on_error("Received message for unknown domain: " + domain + ".");
        return null;
      }
      if (thingy_data == null) {
        delete this._.partials[id];
        delete this._.partials_to_create[id];
        return null;
      }
      if (subkey !== '_') {
        return null;
      }
      thingy_data.delegate.remove(thingy_data.thingy, false);
      delete this._.per_thingy[id];
      return null;
    };

    return Receiver;

  })();

  Heron.Thingy = (function() {
    function Thingy(thingyverse, typename, id, attrs, local_data) {
      var after_construction_functions, f, _i, _len,
        _this = this;
      if (!thingyverse._.make_guard) {
        throw 'Heron.Thingy: Do not create Heron.Thingy directly.  Use Heron.Thingyverse#create';
      }
      if (thingyverse._.per_type[typename] == null) {
        throw "Heron.Thingy: Unknown typename " + typename;
      }
      if (thingyverse._.per_thingy[id] != null) {
        throw "Heron.Thingy: Thingy " + id + " already exists.";
      }
      after_construction_functions = [];
      this._ = {
        thingyverse: thingyverse,
        typename: typename,
        id: id,
        type_data: thingyverse._.per_type[typename],
        removed: false,
        assert_not_removed: function() {
          if (_this._.removed) {
            throw "Heron.Thingy: Trying to do something with removed thingy " + (_this.id());
          }
        }
      };
      this.after_construction = function(f) {
        return after_construction_functions.push(f);
      };
      this._.delegate = this._.type_data.initializer.call(this, attrs, local_data);
      delete this.after_construction;
      thingyverse._.per_thingy[id] = {
        thingy: this,
        delegate: this._.delegate
      };
      for (_i = 0, _len = after_construction_functions.length; _i < _len; _i++) {
        f = after_construction_functions[_i];
        f.call(this);
      }
    }

    Thingy.prototype.id = function() {
      return this._.id;
    };

    Thingy.prototype.typename = function() {
      return this._.typename;
    };

    Thingy.prototype.thingyverse = function() {
      return this._.thingyverse;
    };

    Thingy.prototype.set = function(attrs, local_data) {
      var attr, subkeys,
        _this = this;
      if (local_data == null) {
        local_data = true;
      }
      this._.assert_not_removed();
      subkeys = {};
      for (attr in attrs) {
        subkeys[this._.type_data.attrs[attr]] = true;
      }
      this._.delegate.set(this, attrs, local_data);
      this._.thingyverse.batch(function() {
        var subkey, _results;
        _results = [];
        for (subkey in subkeys) {
          _results.push(_this._.thingyverse._.send_update_subkey(_this, subkey));
        }
        return _results;
      });
      return this;
    };

    Thingy.prototype.get = function() {
      var attr_keys, _ref;
      attr_keys = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      this._.assert_not_removed();
      return (_ref = this._.delegate).get.apply(_ref, [this].concat(__slice.call(attr_keys)));
    };

    Thingy.prototype.gets = function(attr_key) {
      return this.get(attr_key)[attr_key];
    };

    Thingy.prototype.geta = function() {
      var attr_keys, k, values, _i, _len, _results;
      attr_keys = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      values = this.get.apply(this, attr_keys);
      _results = [];
      for (_i = 0, _len = attr_keys.length; _i < _len; _i++) {
        k = attr_keys[_i];
        _results.push(values[k]);
      }
      return _results;
    };

    Thingy.prototype.remove = function(local_data) {
      var prefix,
        _this = this;
      if (local_data == null) {
        local_data = true;
      }
      this._.assert_not_removed();
      this._.delegate.remove(this, local_data);
      prefix = this.id();
      this._.thingyverse.batch(function() {
        var key, subkey, _results;
        _results = [];
        for (subkey in _this._.type_data.subkeys) {
          key = subkey_key(_this.id(), subkey);
          _results.push(_this._.thingyverse._.dictionary["delete"](_this._.thingyverse.domain(), key));
        }
        return _results;
      });
      this._.removed = true;
      delete this._.thingyverse._.per_thingy[this.id()];
      return null;
    };

    return Thingy;

  })();

  Heron.ThingyDelegate = (function() {
    function ThingyDelegate() {}

    return ThingyDelegate;

  })();

  Heron.Thingyverse = (function() {
    function Thingyverse(config) {
      var _ref, _ref1,
        _this = this;
      if (config == null) {
        config = {};
      }
      this._ = {
        dictionary: null,
        domain: null,
        on_sync: function() {},
        on_error: (_ref = config.on_error) != null ? _ref : function(s) {
          throw s;
        },
        ready: (_ref1 = config.ready) != null ? _ref1 : true,
        receiver: null,
        synced: false,
        per_thingy: {},
        per_type: {},
        partials: {},
        partials_subkeys: {},
        partials_to_create: {},
        send_update_subkey: function(thingy, subkey) {
          return send_update_subkey.call(_this, thingy, subkey);
        },
        send_create: function(thingy) {
          return send_create.call(_this, thingy);
        },
        send_create_subkey: function(thingy, subkey) {
          return send_create_subkey.call(_this, thingy, subkey);
        },
        make_thingy: function(typename, id, domain, attrs, local_data, subkeys) {
          return make_thingy.call(_this, typename, id, domain, attrs, local_data, subkeys);
        },
        flush_partials: function() {
          return flush_partials.call(_this);
        }
      };
    }

    Thingyverse.prototype.dictionary = function() {
      return this._.dictionary;
    };

    Thingyverse.prototype.domain = function() {
      return this._.domain;
    };

    Thingyverse.prototype.synced = function() {
      return this._.synced;
    };

    Thingyverse.prototype.connect = function(dictionary, domain, on_sync) {
      if (on_sync == null) {
        on_sync = function() {};
      }
      if (this._.dictionary != null) {
        throw "Already connected to a dictionary.";
      }
      this._.dictionary = dictionary;
      this._.domain = domain;
      this._.on_sync = on_sync;
      this._.receiver = new Receiver(this);
      dictionary.subscribe(this._.domain, this._.receiver);
      return this;
    };

    Thingyverse.prototype.disconnect = function(ready) {
      var data, id, _ref;
      if (ready == null) {
        ready = true;
      }
      if (this._.dictionary == null) {
        throw "Not connected.";
      }
      this._.dictionary.unsubscribe(this._.domain, this._.receiver);
      _ref = this._.per_thingy;
      for (id in _ref) {
        data = _ref[id];
        if (data.delegate.unload != null) {
          data.delegate.unload(data.thingy);
        } else {
          data.delegate.remove(data.thingy);
        }
      }
      this._.per_thingy = {};
      this._.receiver = null;
      this._.dictionary = null;
      this._.domain = null;
      this._.on_sync = null;
      this._.partials = {};
      this._.partials_subkeys = {};
      this._.partials_to_create = {};
      this._.ready = ready;
      return this;
    };

    Thingyverse.prototype.define = function(typename, baseattrs, subkeys, initializer) {
      var attr, attrs, subkey, type_data, _i, _j, _len, _len1;
      if (this._.per_type[typename] != null) {
        throw "Heron.Thingy: " + typename + " already defined.";
      } else {
        type_data = {
          typename: typename,
          initializer: initializer,
          attrs: {},
          subkeys: {}
        };
        type_data.subkeys['_'] = baseattrs;
        for (_i = 0, _len = baseattrs.length; _i < _len; _i++) {
          attr = baseattrs[_i];
          type_data.attrs[attr] = '_';
        }
        for (subkey in subkeys) {
          attrs = subkeys[subkey];
          type_data.subkeys[subkey] = attrs;
          for (_j = 0, _len1 = attrs.length; _j < _len1; _j++) {
            attr = attrs[_j];
            if (type_data.attrs[attr] != null) {
              throw "Heron.Thingy: Duplicatee attr for " + typename + ": " + attr;
            }
            type_data.attrs[attr] = subkey;
          }
        }
        this._.per_type[typename] = type_data;
        return this;
      }
    };

    Thingyverse.prototype.create = function(typename, attrs, local_data) {
      var id, thingy;
      if (attrs == null) {
        attrs = {};
      }
      if (local_data == null) {
        local_data = true;
      }
      if (!this._.ready) {
        throw "Call #ready first.";
      }
      if (!this._.dictionary) {
        throw "Call #connect first.";
      }
      id = Heron.Util.generate_id();
      while (this._.per_thingy[id] != null) {
        id = Heron.Util.generate_id();
      }
      thingy = this._.make_thingy(typename, id, attrs, local_data);
      if (thingy != null) {
        this._.send_create(thingy);
      }
      return thingy;
    };

    Thingyverse.prototype.ready = function() {
      var id, info;
      if (this._.ready) {
        throw "Already ready.";
      }
      for (id in this._.partials_to_create) {
        info = this._.partials[id];
        if (info == null) {
          throw "Insanity error: Partial to create but no info!";
        }
        this._.make_thingy(info.typename, id, info.attrs, false, this._.partials_subkeys[id]);
        delete this._.partials[id];
        delete this._.partials_subkeys[id];
        delete this._.partials_to_create[id];
      }
      this._.ready = true;
      return this;
    };

    Thingyverse.prototype.batch = function(f) {
      return this._.dictionary.batch(f);
    };

    Thingyverse.prototype.begin = function() {
      return this._.dictionary.begin();
    };

    Thingyverse.prototype.finish = function() {
      return this._.dictionary.end();
    };

    Thingyverse.prototype.each_thingy = function(f) {
      var data, id, _ref, _results;
      _ref = this._.per_thingy;
      _results = [];
      for (id in _ref) {
        data = _ref[id];
        _results.push(f(data.thingy));
      }
      return _results;
    };

    Thingyverse.prototype.thingy_by_id = function(id) {
      var _ref;
      return (_ref = this._.per_thingy[id]) != null ? _ref.thingy : void 0;
    };

    return Thingyverse;

  })();

}).call(this);
