// Generated by CoffeeScript 1.6.3
(function() {
  var Heron, c_generate_id_table,
    __hasProp = {}.hasOwnProperty;

  Heron = this.Heron != null ? this.Heron : this.Heron = {};

  c_generate_id_table = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

  Heron.Util = (function() {
    function Util() {}

    Util.rand = function(n) {
      return Math.floor(Math.random() * n);
    };

    Util.generate_id = function(n) {
      var i, l;
      if (n == null) {
        n = 8;
      }
      l = c_generate_id_table.length;
      return ((function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = n - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push(c_generate_id_table[this.rand(l)]);
        }
        return _results;
      }).call(this)).join('');
    };

    Util.keys = function(obj) {
      var k, _results;
      _results = [];
      for (k in obj) {
        if (!__hasProp.call(obj, k)) continue;
        _results.push(k);
      }
      return _results;
    };

    Util.values = function(obj) {
      var k, v, _results;
      _results = [];
      for (k in obj) {
        if (!__hasProp.call(obj, k)) continue;
        v = obj[k];
        _results.push(v);
      }
      return _results;
    };

    Util.extend = function(obj, mixin) {
      var method, name;
      for (name in mixin) {
        method = mixin[name];
        if (obj[name] == null) {
          obj[name] = method;
        }
      }
      return obj;
    };

    Util.include = function(klass, mixin) {
      return this.extend(klass.prototype, mixin);
    };

    Util.empty = function(object) {
      var k;
      for (k in object) {
        return false;
      }
      return true;
    };

    Util.any = function(object) {
      var k, v;
      for (k in object) {
        v = object[k];
        return [k, v];
      }
    };

    return Util;

  })();

}).call(this);
