// Generated by CoffeeScript 1.3.3
(function() {
  var Heron, c_vector_type, _ref;

  c_vector_type = Float32Array;

  Heron = (_ref = this.Heron) != null ? _ref : this.Heron = {};

  Heron.Vector = (function() {

    function Vector() {}

    Vector.vec2 = function(x, y) {
      var v;
      if (x == null) {
        x = 0;
      }
      if (y == null) {
        y = 0;
      }
      v = new c_vector_type(2);
      v[0] = x;
      v[1] = y;
      return v;
    };

    Vector.dup2 = function(v) {
      return Heron.Vector.vec2(v[0], v[1]);
    };

    Vector.equal2 = function(v, b) {
      return v[0] === b[0] && v[1] === b[1];
    };

    Vector.set2 = function(a, x, y) {
      a[0] = x;
      a[1] = y;
      return a;
    };

    Vector.add2 = function(a, b) {
      a[0] += b[0];
      a[1] += b[1];
      return a;
    };

    Vector.sub2 = function(a, b) {
      a[0] -= b[0];
      a[1] -= b[1];
      return a;
    };

    Vector.dot2 = function(a, b) {
      return a[0] * b[0] + a[1] * b[1];
    };

    Vector.negate2 = function(a) {
      a[0] *= -1;
      a[1] *= -1;
      return a;
    };

    Vector.length2 = function(v) {
      return Math.sqrt(Heron.Vector.dot2(v, v));
    };

    Vector.normalize2 = function(a) {
      var n;
      n = Heron.Vector.length2(a);
      a[0] /= n;
      a[1] /= n;
      return a;
    };

    Vector.to_s2 = function(v) {
      return "(" + v[0] + ", " + v[1] + ")";
    };

    Vector.normal2 = function(a) {
      var t;
      t = a[0];
      a[0] = a[1];
      a[1] = -t;
      return a;
    };

    return Vector;

  })();

}).call(this);
